- name: install LAMP Stack
  hosts: local
  remote_user: ubuntu
  become: true
  become_user: root
  gather_facts: true

- name: Include Apache
  import_playbook: apache.yaml

- name: Include MySQL
  import_playbook: mysql.yaml

- name: Include MySQL
  import_playbook: wordpress.yaml
